### PR TITLE
Efi PCI Configuration Space access

### PR DESCRIPTION
**Pull request by jmarcelof**
Implement AcpiOsReadPciConfiguration and AcpiOsWritePciConfiguration on efi environment to help porting the AcpiExec utility.

### CODE REVIEW

**Comment by acpibob** [comment]
This looks good. Lv will look at it, and we'll probably take it directly. Thanks for your help.
Bob

**Comment by zetalog** [comment]
This looks good.
But I need to rebase my acpiexec porting code before trying this.
If you have test results, please also let us know.

Thanks

**Comment by jmarcelof** [comment]
I don't have any tests on this, but it is based on code that I know is working.

Best regards

**Comment by jmarcelof** [comment]
@zetalog do we already have implementation for AcpiOs{Read,Write}Port and AcpiOs{Read,Write}Memory?

Memory access can be made directly, as uefi, during Boot Services, doesn't run with virtual memory adresses...
But, what about Port access? Is that memory-mapped IO?

Thanks

**Comment by acpibob** [comment]
I think we are ready to merge this.

No, we don't have Port I/O or memory access implemented at this time. (we would need to figure out how to do it, so we are looking to any outside UEFI experts to do it, or at least tell us how...)

**Comment by zetalog** [comment]
Hi, Marcelo

If you are interested in ReadPort/ReadMemory, please give them a try and put the implementation into this pull request.
I'll try all of them with acpiexec.

Thanks

**Comment by acpibob** [comment]
Merging. There are a couple of style issues with respect to the ACPICA coding style, but we can take care of these.
Thanks for your help.

**Pull request merged**
