### PR TITLE
ACPICA: drop unneeded initialization value

### PR DESCRIPTION
**Pull request by smalinux**
Do not initialize statics to NULL

### CODE REVIEW

**Review by rafaeljw — CHANGES_REQUESTED** [review]
First off, the changelog only mentions NULL, but the patch changes other cases too.

Second, there are more cases when static vars are initialized to 0 / NULL in the code base, so why not to address them all at once?

**Comment by rafaeljw** [comment]
> My concern with this is that the apparent assumption is that data areas are always initialized to zero –
> which may not be the case on all hosted operating systems.

static/extern variables in C must be initialized to 0 by default as per the language definition and this behavior is relied on quite a bit.

**Comment by rafaeljw** [comment]
Another question is whether or not NULL must be zero, though, and quite frankly I'm not sure, so it probably is prudent to initialize things to NULL (in case it is not 0) explicitly.

**Comment by acpibob** [comment]
So, I think we should ask the poster to finish all of the 0/NULL initializations across ACPICA.

**Comment by rafaeljw** [comment]
I have already done that (I think).

**Comment by acpibob** [comment]
Have not received anything more from the O.P., closing.

**Pull request closed without merging**
