### PR TITLE
iASL: Add CCEL table to both compiler/disassembler

### PR DESCRIPTION
**Pull request by sathyaintel**
Signed-off-by: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>

### CODE REVIEW

**Comment by acpibob** [comment]
We are waiting on this until the major changes for the PHAT table support are finished and committed. However, we will take this patch before the next release of ACPICA this month.

**Comment by sathyaintel** [comment]
@acpibob Did you fix the above issue? If not, I have fixed it and re-submitted the merge request. Please check

https://github.com/acpica/acpica/pull/789

**Comment by acpibob** [comment]
No, I didn’t fix it. I’ll merge your change and try it.
Thanks,
Bob

**Comment by sathyaintel** [comment]
Yes. You need to revert the previous pull request. If you prefer a incremental commit with the fix,I could change it and re-submit the pull request. Please let me know if you want me to do it.

**Comment by acpibob** [comment]
I reverted it from the git command line. Is that a problem?

**Comment by sathyaintel** [comment]
You still need following two patches. If your revert removed one of them, then it is a problem. Can you make sure you have following commits in your tree.

https://github.com/acpica/acpica/commit/10e4763f155eac0c60295a7e364b0316fc52c4f1
https://github.com/acpica/acpica/commit/c717cfd3b368f5068c228a0389df5ec822586fff

**Comment by acpibob** [comment]
Yes, both those commits appear in my gitlog.

**Comment by sathyaintel** [comment]
Since the changes are already there, it does not matter what you reverted.

**Comment by acpibob** [comment]
Do you happen to have a specification for this table (Beginning with “what does CCEL stand for”?

**Comment by sathyaintel** [comment]
https://www.intel.com/content/dam/develop/external/us/en/documents/intel-tdx-guest-hypervisor-communication-interface-1.0-344426-003.pdf
Section 4.3.3 CC-Event Log

CCEL -> Confidential Computing Event Log

**Comment by acpibob** [comment]
I get a “page not found” error when I try to follow the link below.

**Comment by sathyaintel** [comment]
You can also download it from https://www.intel.com/content/www/us/en/developer/articles/technical/intel-trust-domain-extensions.html 

Document title is "Intel TDX Guest-Hypervisor Communication Interface"

Or you can download document from https://cdrdv2.intel.com/v1/dl/getContent/726790

**Pull request merged**
