### PR TITLE
CDAT updates

### PR DESCRIPTION
**Pull request by davejiang**
A spelling correction for CDAT definition and the other adding additional CDAT defines.

### CODE REVIEW

**Review by AlisonSchofield — APPROVED** [review]
Reviewed by alison.schofield@intel.com

**Comment by davejiang** [comment]
@sacdintel I noticed that only 1 of the 2 patches are merged in. https://github.com/intel-sandbox/cxl/commit/8557c5673dbff1b09044ef356035b2e24319d6a0 was missed. Can you please also pick up that patch? Thank you!

**Comment by sacdintel** [comment]
Hi Dave,

I apologize if 1 of your 2 commits was not picked up for merge. I am not sure if there is some bug in GitHub or not, but I do see from my end that 2 commits were merged from this PR to our main branch. I am not sure if there is some script you wrote or if you have ported those 2 commits from somewhere else to ACPICA, but I am not exactly sure how GitHub works under the hood in those scenarios. I am attaching some screenshots that might help you understand what could have gone wrong or what needs to be done now. Please take a look and advise me on my next steps. Also I am not sure if and how I can merge the commit link from your comment earlier today directly into ACPICA. Thanks! 
PR874_files_changed
PR874_aggregated
PR_874_commit_merged

**Comment by davejiang** [comment]
@sacdintel  I'm not sure either. To make things easier, why don't I put the missed patch on top of latest ACPICA code and create a new pull request? Would that work?

**Comment by sacdintel** [comment]
Yes, that would work and it will be the most simple & straightforward solution to this problem rather than having to deal with the intricacies of GitHub! Thanks! I'll merge the new PR as soon as I can!

**Comment by davejiang** [comment]
@sacdintel https://github.com/acpica/acpica/pull/898

**Pull request merged**
