### PR TITLE
Acpica vars

### PR DESCRIPTION
**Pull request by zetalog**
BZ 1335.

Fix a design issue in parsing variable arguments.

### CODE REVIEW

**Comment by acpibob** [comment]
Please send/post a test case for ASLTS.

**Comment by zetalog** [comment]
It's reported by CoverityTool.
ASLTS shouldn't be able to detect such memory leak.
It can only happen when memory consumption in the system is very high.
And field allocation returns NULL.
Running the following AML:
``DefinitionBlock ("./dsdt.aml", "DSDT", 2, "INTEL ", "HSW-LPT", 0x00000000)
{
    Method (MAIN, Serialized)
    {
        OperationRegion (OPRG, PCI_Config, Zero, 0x10)
        Field (OPRG, DWordAcc, NoLock, Preserve)
        {
            Offset (0x00), 
            FLD1,   1, 
            FLD2,   1, 
        }
        Store (1, FLD1)
    }
}``
With the following change should be able to reproduce:
``diff --git a/source/components/parser/psargs.c b/source/components/parser/psargs.c
index 83f8d66..fb56d95 100644
--- a/source/components/parser/psargs.c
+++ b/source/components/parser/psargs.c
@@ -600,7 +600,7 @@ AcpiPsGetNextField (
     ACPI_PARSE_STATE        *ParserState)
 {
     UINT8                   *Aml;
-    ACPI_PARSE_OBJECT       *Field;
+    ACPI_PARSE_OBJECT       *Field = NULL;
     ACPI_PARSE_OBJECT       *Arg = NULL;
     UINT16                  Opcode;
     UINT32                  Name;
@@ -610,6 +610,7 @@ AcpiPsGetNextField (
     UINT32                  PkgLength;
     UINT8                   *PkgEnd;
     UINT32                  BufferLength;
+    static UINT8            Count = 0;
 
 
     ACPI_FUNCTION_TRACE (PsGetNextField);
@@ -653,7 +654,11 @@ AcpiPsGetNextField (
 
     /* Allocate a new field op */
 
-    Field = AcpiPsAllocOp (Opcode, Aml);
+    if (Count == 0)
+    {
+        Field = AcpiPsAllocOp (Opcode, Aml);
+        Count++;
+    }
     if (!Field)
     {
         return_PTR (NULL);
``

**Comment by acpibob** [comment]
Please explain the fix, thanks.

**Comment by zetalog** [comment]
In AcpiPsGetNextArg():

Allocated ACPI_PARSE_OBJECT (Arg) needn't be freed when it is set to the return value:
    *ReturnArg = Arg;

The parser main loop automatically chains all arguments with AcpiPsAppendArg().
And automatically frees arguments when the parse loop ends.

The problem is AcpiPsGetNextArg() contains a loop for ARGP_FIELDLIST:
            while (ParserState->Aml < ParserState->PkgEnd)
            {
                Field = AcpiPsGetNextField (ParserState);
                if (!Field)
                {
                    return_ACPI_STATUS (AE_NO_MEMORY);
                }

                if (Prev)
                {
                    Prev->Common.Next = Field;
                }
                else
                {
                    Arg = Field;
                }
                Prev = Field;
            }
This means in this case, AcpiPsGetNextArg() now doesn't return an single TermArg, but returns a list of TermArg.
Then the parse loop framework's parse object deletion automation is not working.
When a failure is encountered during field parse, the loop can be broken, and the parse objects allocated in this function won't be returned to its caller and won't be appended by AcpiPsGetNextArg().
They are leaked.

The root cause fix is to make sure AcpiPsGetNextArg() always return one single TermArg.
Let me describe later about how this can be done.

**Comment by zetalog** [comment]
In AML grammar, there are variable arguments for some Terms.
For example:
1. term lists (scope related):
```
DefScope := ScopeOp PkgLength NameString TermList
DefDevice := DeviceOp PkgLength NameString ObjectList
DefMethod := MethodOp PkgLength NameString MethodFlags TermList
DefPowerRes := PowerResOp PkgLength NameString SystemLevel ResourceOrder ObjectList
DefProcessor := ProcessorOp PkgLength NameString ProcID PblkAddr PblkLen ObjectList
DefThermalZone := ThermalZoneOp PkgLength NameString ObjectList
DefPackage := PackageOp PkgLength NumElements PackageElementList
DefVarPackage := VarPackageOp PkgLength VarNumElements PackageElementList
```
2. buffer
```
DefBuffer := BufferOp PkgLength BufferSize ByteList
```
3. logical namespace modifiers
```
DefWhile := WhileOp PkgLength Predicate TermList
DefElse := ElseOp PkgLength TermList
DefIf := IfOp PkgLength Predicate TermList
```
Above is converted from:
```
DefElse := Nothing | <ElseOp PkgLength TermList>
DefIfElse := IfOp PkgLength Predicate TermList DefElse
```
By adding:
```
DefOptionalElse : Nothing | DefElese
DefIfElse := DefIf DefOptionalElse
```
In order to put TermList as the last element.
4. field lists
```
DefBankField := BankFieldOp PkgLength NameString NameString BankValue FieldFlags FieldList
DefField := FieldOp PkgLength NameString FieldFlags FieldList
DefIndexField := IndexFieldOp PkgLength NameString NameString FieldFlags FieldList
```

See the variable length TermArg is always the last element.
And 1/3 has been handled in the main parse loop, 2 is handled in buffer parsing.
4 is the only case now contains bugs.

**Comment by zetalog** [comment]
Since the variable length TermArg is always the last element and the number of its elements are always determined by PkgLength.
This fix adds a "VarArgs" indication and sets it to "FALSE" when PkgLength sized arguments are not fully handled by the parser. So when VarArgs == FALSE, we needn't advance argument to the next element:
```
+            if (!WalkState->VarArgs)  
+            {  
+                INCREMENT_ARG_LIST (WalkState->ArgTypes);  
+            }  
```
This effectively move **ARGP_FIELDLIST** parsing from **AcpiPsGetNextArg()** to its caller, making **AcpPsGetNextArg()** always returning one single TermArg.

**Comment by zetalog** [comment]
There are 6 places where **INCREMENT_ARG_LIST** is called:
```
1. aslwalks.c(471):            INCREMENT_ARG_LIST (RuntimeArgTypes);
2. aslwalks.c(631):            INCREMENT_ARG_LIST (RuntimeArgTypes2);
3. exresop.c(458):        INCREMENT_ARG_LIST (ArgTypes);
4. psloop.c(282):            INCREMENT_ARG_LIST (WalkState->ArgTypes);
5. psobject.c(333):        INCREMENT_ARG_LIST (WalkState->ArgTypes);
6. psobject.c(358):    INCREMENT_ARG_LIST (WalkState->ArgTypes);
```
and 2 places where **AcpiPsGetNextArg()** is called:
```
psloop.c(270):            Status = AcpiPsGetNextArg (WalkState, &(WalkState->ParserState),
psobject.c(325):        Status = AcpiPsGetNextArg (WalkState, &(WalkState->ParserState),
```
We only need to fix those both are called.
So I fixed psloop.c(282) which is the only place fixing FIELDLIST parsing.
psobject.c(358) is not related to FIELDLIST parsing.

**Comment by zetalog** [comment]
Hope the above explanation is useful for reviewing the change.
ASLTS validation show no regression before/after applying this commit.

**Comment by timofonic** [comment]
@acpibob @zetalog Any hopes about merging? Does changes like this limit legitimate ACPI modification and testing (like fixing broken ACPI tables, for example)?

**Comment by zetalog** [comment]
This fix is OK from my point of view, maybe Erik can tell if it breaks ASLTS.
If not, probably this should be merged.

**Comment by timofonic** [comment]
@zetalog @acpibob @SchmErik What about this pull request now? Some months have passed since I asked about it. I'm curious if it'll get merged or not.

**Comment by acpibob** [comment]
Closing for now, due to what we perceive as very high risk.

**Pull request closed without merging**
