### PR TITLE
Remove extern prototypes in achaiku.h file

### PR DESCRIPTION
**Pull request by ElyesH**
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>

### CODE REVIEW

**Comment by rafaeljw** [comment]
What's wrong with using 'extern' here?  Is it just inconsistent or is there more to it?

**Comment by acpibob** [comment]
I'd be a bit cautious about this, since the achaiku.h file comes directly from the haiku project.

**Comment by ElyesH** [comment]
"extern" keyword is used implicitly for functions.
it is always implied with function declarations.

**Comment by acpibob** [comment]
Is this true for all C compilers?

**Comment by ElyesH** [comment]
it is for gcc, but for the others I'm not sure.

**Pull request merged**
