### PR TITLE
IORT: Updates for revision E.d

### PR DESCRIPTION
**Pull request by shamiali2008**
IORT revision is now updated to E.d (ARM DEN 0049E.d) and
contains a few additions like,
    -Added descriptor in the root complex node for specifying
     PASID width supported by the root complex.
    -Updated RMR node Flags field.
    -Introduced memory access attributes in the RMR node.

Please note that IORT Rev E.c is deprecated and not supported.

Signed-off-by: Shameer Kolothum <shameerali.kolothum.thodi@huawei.com>

### CODE REVIEW

**Comment by shamiali2008** [comment]
The IORT Rev E.d doc can be found here,
https://developer.arm.com/documentation/den0049/ed/

Thanks,
Shameer

**Comment by acpibob** [comment]
We would like these defines to be all upper case.

For example:


+#define ACPI_IORT_RMR_ATTR_DEVICE_nGnRnE   0x00

**Comment by shamiali2008** [comment]
This is the way normally device memory is represented in Arm specification
documents and kernel as well.
eg:
https://elixir.bootlin.com/linux/v4.5/source/arch/arm64/include/asm/pgtable.h#L72

So would like to keep that to avoid any confusion, if it is Ok.

Thanks,
Shameer

**Comment by shamiali2008** [comment]
Yes, Ideally would like to keep the lower case. 
But if ACPICA convention is to capitalise #defines, I am not sure what is the best way here.

@rmurphy-arm  Any thoughts? Can we go with ACPICA convention here?

Thanks.

**Comment by rmurphy-arm** [comment]
Sure, there's no need to break convention - ACPICA isn't bound by Arm's technical writing guidelines, after all. I'm just keen that whatever ACPICA's readable identifier for value 0x5 is, it explicitly captures that it's Write-Back Cacheable. We don't really expect to need yet more Normal memory types with further varieties of cacheablility, but we've intentionally left room to define additional values later if people do demand them.

**Comment by shamiali2008** [comment]
Ok. I will close this one and submit another one taking care of all the above comments.

Thanks.

**Pull request closed without merging**
