### PR TITLE
ACPICA: Add Codefirst support for Mantis IDs: [3706,4557]

### PR DESCRIPTION
**Pull request by lpieralisi-linaro**
Add ACPICA support to handle Codefirst changes (Mantis ID: 3706 and 4557),   
both adding flags to the ARM GIC MADT table entries.

### CODE REVIEW

**Comment by sacdintel** [comment]
I think the ASWG Mantis ID is 2422 for the corresponding issue opened by Souvik Chakravarty. 
https://mantis.uefi.org/mantis/view.php?id=2422
I just needed that approval clarification before I can merge this PR, thanks Lorenzo! I can go ahead and review it now.

**Comment by sacdintel** [comment]
Looks good, thanks! I will go ahead and merge it now!

**Comment by lpieralisi-linaro** [comment]
Thank you very much !! Should I send the linux kernel header myself for upstream Linux or it is something that is automatically done ?

**Comment by sacdintel** [comment]
I am not exactly sure about this process of porting and backporting ACPICA changes to the kernel, so adding Rafael to help answer it better than me. From what I have heard is that Rafael ports all the ACPICA changes to the next Linux kernel X.x (6.8 or so for now) so I am hoping your ACPICA changes should carry forward automatically in the next kernel release cycle. Thanks!

Kind regards,
Saket Dumbre

Software Engineer
Intel (Hillsboro, Oregon)
Emergency: ***@***.******@***.***> | (480) 434-5969

**Pull request merged**
