### PR TITLE
iASL/MADT: Add dump and compile support for LoongArch APICs

### PR DESCRIPTION
**Pull request by lvjianmin-loongson**
The previous patch(MADT: Add LoongArch-specific APICs support), has added LoongArch-specific APICs support, but lack of dumping and compiling for LoongArch APICs in MADT when using iasl tool, so add code to support it.

### CODE REVIEW

**Comment by lvjianmin-loongson** [comment]
@acpibob 
The patch in this PR has been reviewed before, but since some conflicts which are really hard to be addressed are included in previous PR, so a new PR here is created for previous reviewed patch. 

Thanks!

**Comment by sacdintel** [comment]
Hi Jianmin,
Thanks for the PR. Does the previous already-merged PR need to be reverted first or something and then this PR applied? Or should the already-merged PR still be left as it is (i.e. merged) and then this PR applied on top of it? Also this PR needs to be applied first and then your other PR #866 right? And not apply the PR #818 since PR #866 addresses it? Please let me know what needs to be done and the answers. Thanks!
- Saket Dumbre

**Comment by lvjianmin-loongson** [comment]
> Hi Jianmin, Thanks for the PR. Does the previous already-merged PR need to be reverted first or something and then this PR applied? Or should the already-merged PR still be left as it is (i.e. merged) and then this PR applied on top of it? Also this PR needs to be applied first and then your other PR #866 right? And not apply the PR #818 since PR #866 addresses it? Please let me know what needs to be done and the answers. Thanks!
> 
> * Saket Dumbre

The patch in this PR has nothing to do with the issue patch(maybe it needs to be reverted) related to #866 and #818. So it does not matter to apply this PR whether it's on top ot it or not. And if a reverted patch or my fixed patch in #866 is applied, #818 will not be needed.

BTY, should we apply a reverted patch or fixed patch? If apply a fixed patch, I'll send next changed version. So, please let me know how should I do next, thanks!

**Comment by sacdintel** [comment]
Hi Jianmin,
Revert - used usually to rollback some changes that were already implemented
Fixed - that is usually like a whole solution addressed for some problem to be fixed
I am not sure what you exactly mean by the 2 separate patch types. If you want to undo something that is already a part of ACPICA right now that  was a PR from you before, you can comment below with the PR# and I can revert that PR for you. If you wish to continue making changes for constant improvement, you can just add more commits to this same PR that reflect the proposed code changes that I can merge when the builds are clean and the proposed new/changed functionality works fine. 
I like to keep things simple and I am a fairly bit new to this role as well (ACPICA maintainer & developer). I would like more info/clarity most of the times when implementations are still broken and I can also try my best from my end to make sense of the new changes and help figure contributors out if they are in a difficult situation. It is a collaboration work after all! Thanks!
- Saket Dumbre

**Comment by lvjianmin-loongson** [comment]
> Hi Jianmin, Revert - used usually to rollback some changes that were already implemented Fixed - that is usually like a whole solution addressed for some problem to be fixed I am not sure what you exactly mean by the 2 separate patch types. If you want to undo something that is already a part of ACPICA right now that was a PR from you before, you can comment below with the PR# and I can revert that PR for you. If you wish to continue making changes for constant improvement, you can just add more commits to this same PR that reflect the proposed code changes that I can merge when the builds are clean and the proposed new/changed functionality works fine. I like to keep things simple and I am a fairly bit new to this role as well (ACPICA maintainer & developer). I would like more info/clarity most of the times when implementations are still broken and I can also try my best from my end to make sense of the new changes and help figure it out with contributors if they are in a difficult situation. It is a collaboration work after all! Thanks!
> 
> * Saket Dumbre

Ok, got it.  Again, the patch in the PR has nothing to do with the issue patch and can be applied.  PR #866 will be not needed, and I'll close it. Please revert the patch("Events: Support fixed pcie wake event") in PR #757, which has been reverted in linux kernel by linus.

Anything I didn't make it clear, please let me know.
Thanks!

**Comment by sacdintel** [comment]
Thanks for the clarification! Now everything makes a lot of sense to me! One final question though: what would you like to be done to the already merged PR #826 ? Should it stay as it is? Or do you want me to revert that? Please let me know, thanks! From the looks of it, it might need to stay for enabling support in Linux, but if you or any of your other co-workers have different plans, just in that case I am asking. Thanks!

**Comment by lvjianmin-loongson** [comment]
> Thanks for the clarification! Now everything makes a lot of sense to me! One final question though: what would you like to be done to the already merged PR #826 ? Should it stay as it is? Or do you want me to revert that? Please let me know, thanks! From the looks of it, it might need to stay for enabling support in Linux, but if you or any of your other co-workers have different plans, just in that case I am asking. Thanks!

Yes, I'm sure that PR #826 which has been merged should stay as it is.

Thanks very much.

**Pull request merged**
