### PR TITLE
iASL: Add CCEL table to both compiler/disassembler

### PR DESCRIPTION
**Pull request by sathyaintel**
Signed-off-by: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>

### CODE REVIEW

**Comment by acpibob** [comment]
I've got resolved conflicts with dmtbinfo3.c -- looks like I need to revert the previous pull request.

**Comment by sathyaintel** [comment]
Yes. You need to revert the previous pull request. If you prefer a incremental commit with the fix,I could change it and re-submit the pull request. Please let me know if you want me to do it.

**Comment by acpibob** [comment]
Yes, I would prefer an incremental commit.

**Comment by sathyaintel** [comment]
Ok. Please ignore this pull request. Let me fix it based on the master branch and re-submit the pull request

**Comment by sathyaintel** [comment]
It is fixed now as separate commit. Please pull my latest changes.

**Comment by acpibob** [comment]
I just reverted the pull request.

**Comment by acpibob** [comment]
I get a "merged" notice for #778. What about #789?

**Comment by acpibob** [comment]
I reverted the entire #789 from the git command line.

**Comment by sathyaintel** [comment]
It seems you have the change.

https://github.com/acpica/acpica/commit/3103c689316a41e3b16d40cc8bcbbb804b8d961a

**Comment by acpibob** [comment]
OK. the changes enable the compile to work.

**Pull request merged**
