### PR TITLE
Add support for AMD Secure Processor Table (ASPT) version 1

### PR DESCRIPTION
**Pull request by jepio**
This follows the ASPT Rev1 Specification, I am working on getting that spec uploaded somewhere public.
The structure definitions can also be found in public windows acpi headers:
* https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/acpitabl/ns-acpitabl-aspt_table
* https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/acpitabl/ns-acpitabl-aspt_entry_header
* https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/acpitabl/ns-acpitabl-aspt_entry
* https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/acpitabl/ns-acpitabl-aspt_entry_asp_global_registers
* https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/acpitabl/ns-acpitabl-aspt_entry_sev_mailbox_registers
* https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/acpitabl/ns-acpitabl-aspt_entry_acpi_mailbox_registers

### CODE REVIEW

**Comment by acpibob** [comment]
Please make this into a pull request.
Thanks,
Bob

**Comment by jepio** [comment]
> Please make this into a pull request. Thanks, Bob

This is already part of this PR.

**Comment by acpibob** [comment]
Ok, got it.

**Comment by jepio** [comment]
For future reference, this is the spec url: https://www.amd.com/system/files/TechDocs/58028_1.00-PUB.pdf

**Pull request merged**
