### PR TITLE
Edk2 stdlib/windows

### PR DESCRIPTION
**Pull request by zetalog**
Collction of all EDK2 StdLib and Windows build support from #184 and #286.
I'll close the others.

### CODE REVIEW

**Comment by zetalog** [comment]
Tested the following 3 builds:

1. gnu-efi
2. edk2 with stdlib
3. edk2 without stdlib

**Comment by acpibob** [comment]
Need to handle overflow with the multiply operator (and add operator when implemented)

**Comment by zetalog** [comment]
Build test with UDK2015:
[efi-stdlib-builds.txt](https://github.com/acpica/acpica/files/1144296/efi-stdlib-builds.txt)

**Comment by zetalog** [comment]
I just dropped the last commit which creates the only user of our assembly math64 support.
So there is no user linking to the assembly math64.
I'll enhance the assembly according to your needs and prepare a different pull request for you.
For this pull request, you can safely merge it so our work won't be dependent on each others'.

Thanks

**Comment by zetalog** [comment]
It's not safe, I need to fix this function to make it compliant to crt generation:

```
ACPI_STATUS
AcpiUtShortMultiply (
    UINT64                  Multiplicand,
    UINT32                  Multiplier,
    UINT64                  *OutProduct)
{
    UINT64_OVERLAY          MultiplicandOvl;
    UINT64_OVERLAY          Product;
    UINT32                  Carry32;


    ACPI_FUNCTION_TRACE (UtShortMultiply);


    MultiplicandOvl.Full = Multiplicand;

    /*
     * The Product is 64 bits, the carry is always 32 bits,
     * and is generated by the second multiply.
     */
    ACPI_MUL_64_BY_32 (0, MultiplicandOvl.Part.Hi, Multiplier,
        Product.Part.Hi, Carry32);

    ACPI_MUL_64_BY_32 (0, MultiplicandOvl.Part.Lo, Multiplier,
        Product.Part.Lo, Carry32);

    Product.Part.Hi += Carry32;

    /* Return only what was requested */

    if (OutProduct)
    {
        *OutProduct = Product.Full;
    }

    return_ACPI_STATUS (AE_OK);
}
```

I'll fix it and update the pull request.

**Comment by zetalog** [comment]
Hi, Bob

I just added the test code:
```
#include <assert.h>

    UINT64                  operand = 0xFFFFFFFFFFFFFFFF;
    UINT32                  multiplier = 2;
    UINT64                  result;
    UINT64                  expected;

    AcpiUtShortMultiply (operand, multiplier, &result);
    expected = operand * multiplier;
    if (result != expected)
        assert (FALSE);
```

The assert is not triggered, both expected and result is 0xFFFFFFFFFFFFFFFE.
The AcpiUtShortMultiply() is compliant to CRT behavior.

So it is safe to merge.

**Comment by zetalog** [comment]
If you want to detect overflow for add/multiply for operand object conversion code, you should know whatever the assembly one is efficient or not, no user is linking to it:

Our windows version links to MSVC clibrary.
EFI stdlib version links to EFI StdLib.
GNU EFI/EDK2 nostdlib version links to BaseLib.

You just need to implement it in AcpiUtStrtoul64() before calling this low-level one.
Or implement another wrapper calling this low level one.

Thanks

**Pull request merged**
