### PR TITLE
Fix CFMWS decoding and add CXIMS decoding

### PR DESCRIPTION
**Pull request by zhang-rui**
Fix CFMWS decoding and add CXIMS decoding.

Please kindly review.

### CODE REVIEW

**Comment by sacdintel** [comment]
Hi Rui,

This turned out to be a lot more work than I had imagined, but thanks for this PR. I thought it was going to be a quick fix but apparently a few structures and logic were entirely missing from our CEDT implementation as it turns out! Will merge it after Alison does a code review and tests it out, thanks!

**Review by AlisonSchofield — COMMENTED** [review]
Thanks Rui!  
Can you add to the commit log the user visible impact of this fix.   ie. a before and after snapshot of decoded CFMWS.

**Review by AlisonSchofield — COMMENTED** [review]
It may be useful to clarify that this is for acpitools dump and decode only and does not affect the CXIMS structures included in the acpi tables.

**Review by AlisonSchofield — COMMENTED** [review]
Similar comment.  Please state what works now, that didn't work previously. Thanks!

**Comment by zhang-rui** [comment]
Hi @AlisonSchofield  @sacdintel , patch refreshed based on Alison' feedback, please kindly review.

**Comment by sacdintel** [comment]
Thanks @AlisonSchofield for the review! This looks good now @zhang-rui so I will go ahead and merge it now!

**Comment by zhang-rui** [comment]
Thanks @sacdintel .

**Pull request merged**
