### PR TITLE
Acpica package2

### PR DESCRIPTION
**Pull request by zetalog**
ASLTS fixes that need to be re-evaluated.
This is split from #189.

### CODE REVIEW

**Comment by jacknlliu** [comment]
What's the status of this patch? Origin problems still exists in `Fedora` distribution with kernel `4.11.8`.

**Comment by zetalog** [comment]
In order not to modify ASLTS so much (correcting ASLTS shouldn't be a part of the fix), we are trying to use a different mechanism to fix this problem. Bob generated a prototype for the new solution and I'm reviewing and testing it.

**Comment by jacknlliu** [comment]
@zetalog  thank you for sharing your process.

**Comment by zetalog** [comment]
Note commits in this pull request is not correct from ASLTS' point of view.
If someone wants to fix this issue in his local copy, he should only merge  #189.

**Comment by timofonic** [comment]
@zetalog @acpibob Any news about when this stuff will me merged upstream?

**Comment by zetalog** [comment]
As the new solution is upstreamed, we can have ASLTS unchanged for now.
Until a real need is reported, this ticket will remain closed.

**Comment by mirh** [comment]
Any update on #330?
Would be cool if it could make for 4.15

**Comment by SchmErik** [comment]
We are currently working on #330

**Comment by timofonic** [comment]
@zetalog Any news about the ASLTS changes? Are there ASLTS changes to be merged? I hope some improvements may help me to fully decompile the ACPI table of my laptop easily, I'm unable to do it currently :(

**Comment by acpibob** [comment]
What is the problem you are seeing with the disassembly of your table(s)?

We would like to see the acpi tables, please send us an acpidump of the machine.
Thanks,
Bob

**Comment by acpibob** [comment]
Generally, the list of pull requests are sitting there pending:
Code/design review
Check for obsolescence
Very low priority, simply a placeholder
Code that is in fact obsolete, but we are holding it in the list in case it is ever needed.

In other words, just because something is in the pull request list, it does not mean that it will be ever integrated into ACPICA.

We have a very small team here, and we have to carefully prioritize our tasks.

That said, if you are having a problem with the iASL disassembler, please send us the AcpiDump for the machine.

Bob

**Pull request closed without merging**
