### PR TITLE
dsfield.c:  Fix dead assignment

### PR DESCRIPTION
**Pull request by ElyesH**
Return the value stored to 'Status' instead.

Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>

### CODE REVIEW

**Comment by SchmErik** [comment]
Why are you suggesting this change? Is there some other problem that you're seeing that this code fixes?

**Comment by ElyesH** [comment]
at line #347 , "Status" is set = to "AE_OK", but it is never used.

**Comment by SchmErik** [comment]
Out of curiosity, were you using any static analysis tools to uncover this?

**Comment by ElyesH** [comment]
clang scan build: 
https://clang-analyzer.llvm.org/

**Comment by ElyesH** [comment]
I don't know why this is mixed with other pull request.
I did a mistake maybe, but as I'm not comfortable with github, don't know how to fix it. (sorry)
so maybe the best solution is to close current request ?

**Comment by acpibob** [comment]
You might try closing this one and opening up a new one.

**Comment by ElyesH** [comment]
sorry,
current patch is mixed.
I probably did a mistake and I don't know how to fix.

**Pull request closed without merging**
