### PR TITLE
iASL: Add support for the AEST V2 table

### PR DESCRIPTION
**Pull request by winterddd**
AEST V2 was published [1], add V2 support based on AEST V1.

[1]: https://developer.arm.com/documentation/den0085/latest/

### CODE REVIEW

**Comment by sacdintel** [comment]
Please also don't forget to update the table template under dttemplate.h and please address my concern regarding the coding style mismatch in the code review, thanks a lot!

**Comment by sacdintel** [comment]
Updating the template is a big hint (although not a hard evidence) to me that the PR for another (non-x86 i.e. not my system) architecture works fine, meaning the advertised table changes are compiled and disassembled correctly as intended since we don't have the means to test a system with every possible permutation and combination of OS, platform, architecture, C compiler etc. that is supported by ACPI.

**Comment by winterddd** [comment]
update:
- update AEST template
- follow ACPICA coding style

**Comment by sacdintel** [comment]
Looks good now, thanks a lot! Ready to merge it!

**Pull request merged**
