### PR TITLE
Efi mem and I/O access services

### PR DESCRIPTION
**Pull request by jmarcelof**
Implementation of OS services to access physical memory and I/O on uefi environment.

Memory access is made directly (no virtual address translation needed) and ports are considered memory-mapped.

Marcelo

### CODE REVIEW

**Comment by zetalog** [comment]
The 2nd patch is not correct.
AcpiOsRead/WritePort should only be used to access IO ports (aka, SystemIo address space operation regions).

Thanks

**Comment by jmarcelof** [comment]
Now I understand what you mean, I saw the address range at hwvalid.c. Then I'll further analyse this issue and see what we can do about.

Thanks

**Comment by jmarcelof** [comment]
The 2nd patch is fixed now. I made some primitive tests accessing ports of the RTC region and it seems to be correct.

**Comment by zetalog** [comment]
One thing I do not understand for UEFI is:
It seems UEFI only provides IO functionalities related to the EFI protocols.
Either BRIDGE_IO, PCI_IO or DEVICE_IO, etc.

Which makes IO read/write a device specific manner.

Shouldn't there be a device independent way to achieve IO operations?

**Comment by jmarcelof** [comment]
Actually, the EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL works, for our purposes, as a wrapper to the EFI_CPU_IO_PROTOCOL which has the 'in/out instructions'. Others "specific-device-related EFI protocols" employ EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL to implement their I/O.

So, the independent way of achieving IO operations is primarily by using EFI_CPU_IO_PROTOCOL, but as ACPICA will run after EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL is ready it's better to use it.

Thanks

**Comment by zetalog** [comment]
However ACPI allows SystemIo opregion accesses to be performed on device IO regions other than those owned by the root bridge.
And Linux implements it with in/out instructions:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/acpi/osl.c?id=2c85025c#n632

**Comment by zetalog** [comment]
I doubt that if AML code enables a PCI device, and accesses its SystemIo operation region in an _INI function. Can EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL handle it?

Thanks
Lv

**Comment by jmarcelof** [comment]
I'm pretty sure it'll work fine but I can replace the RootBridgeIo by the CpuIo protocol if you think it's better.

But I'm no more so sure about the first patch (the physical memory access one). Maybe we'll need to use RootBridgeIo (or CpuIo) too.
Keep me updated about your tests and I'll fix it.

And if there's anything else that I could help just let me know.
Thanks

**Comment by acpibob** [comment]
does this need to be updated, or is it obsoleted by other EFI changes?

**Comment by zetalog** [comment]
The PR didn't pass the test.
However you can close it.
I've collected jmarcelof's code in my local repo with his authorship kept.
I'll take care of helping him to upstream the changes.

**Comment by acpibob** [comment]
Closing as per Lv's comment

**Pull request closed without merging**
