### PR TITLE
debugger: fix build warnings on set but not used variable NumStatements

### PR DESCRIPTION
**Pull request by ColinIanKing**
When building the Linux kernel integrated version of ACPICA with clang
we get warnings that NumStatements is set but not used. Fix this by
adding more #if guarding around this variable so that it is only
declared and set when it is being required.

Fixes Linux clang build warning:
warning: variable 'num_statements' set but not used [-Wunused-but-set-variable]

Signed-off-by: Colin Ian King <colin.king@canonical.com>

### CODE REVIEW

**Comment by acpibob** [comment]
we need a bit of clarification.

So, this is a build that includes the AML debugger but not the disassembler?

If so, probably the entire "List" command should go away in this case.

**Comment by ColinIanKing** [comment]
I believe this in the AML debugger mode, as when the disassembler mode is enabled with  ACPI_DISASSEMBLER defined, then the reference to num_statements is being made and the warning won't occur in that latter case.

**Comment by acpibob** [comment]
So it sounds like the debugger (can be) in the kernel, but the disassembler is not.

I'm going to completely disable the "List" command in this case. This is the only caller for AcpiDbDisassembleAml.

**Comment by ColinIanKing** [comment]
Hrm.  Is the "List" command useful in the kernel debugger?  So disabling it may be reducing functionality to kernel / ACPI developers.

**Comment by ColinIanKing** [comment]
Ah, OK, understood.  In which case yes, List can be removed :+1:

**Comment by acpibob** [comment]
I can take it from here.

**Comment by acpibob** [comment]
It looks like the "Debug" (single-step) command depends on the disassembler also.

**Comment by acpibob** [comment]
Closing as per comments above.

**Pull request closed without merging**
