### PR TITLE
Use ACPI_GET_FUNCTION_NAME

### PR DESCRIPTION
**Pull request by ElyesH**
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>

### CODE REVIEW

**Comment by rafaeljw** [comment]
Is __func__ universally recognized by all compilers that can be used to build ACPICA?

**Comment by rafaeljw** [comment]
I meant '__func__'

**Comment by acpibob** [comment]
Yes, I don't think that all compilers support __func__

**Comment by acpibob** [comment]
Got it, thanks.
Bob

**Pull request merged**
