### PR TITLE
iASL: parse valid package elements returned by predefined control met…

### PR DESCRIPTION
**Pull request by SchmErik**
…hods

Signed-off-by: Erik Kaneda <erik.kaneda@intel.com>

### CODE REVIEW

**Comment by acpibob** [comment]
From the ACPI spec:
Package (NumElements) {PackageList} =>Package
...
"If NumElements is present and greater than the number of elements in the PackageList, the default entry of type Uninitialized is used to initialize the package elements beyond those initialized from the PackageList."

It doesn't look like this change handles the case above, but I'm not sure.

**Comment by SchmErik** [comment]
Thanks for bringing this up. No, this PR doesn't address this. It just prevents a null dereference. @acpibob, are you saying that this behavior should be implemented in the interpreter or should the uninitialized elements be inserted in the AML bytecode?

**Comment by acpibob** [comment]
I think it should be implemented in the interpreter; the code already exists somewhere, AFAIK.

Which predefined name is this from?

**Comment by SchmErik** [comment]
The original report was from _PSL

**Comment by SchmErik** [comment]
Here's the dsdt from the original report: https://github.com/acpica/acpica/files/5049983/DSDT_crash.zip

**Pull request merged**
