### PR TITLE
Documents: Fix some very minor typos.

### PR DESCRIPTION
**Pull request by Jnosh**
Consistently use the verbs delete & purge in the descriptions of AcpiOsDeleteCache & AcpiOsPurgeCache.

If pull requests against the binary word document are not desired I could also just specify the small edits I did here.
Also should I create an updated pdf of the word document as well and include it in the pull request?

Thanks for reviewing.

### CODE REVIEW

**Comment by Jnosh** [comment]
I updated the pull request with some additional small fixes.

**Comment by acpibob** [comment]
We'll roll these into the next release this month.
thanks.

**Comment by acpibob** [comment]
We will pull this in when we update the document with some new things that we have.

**Comment by acpibob** [comment]
Can you post the exact changed text? We have the document open at this time, but we don't want to just checkin a new version of the doc for a few small typos (it is binary and an entire new copy is then entered into our repository).

**Comment by acpibob** [comment]
I've got all the cache stuff; for anything else, please post the changed text.
thanks.

**Comment by acpibob** [comment]
Also got the lock fix and the handful of extraneous periods.

**Comment by acpibob** [comment]
Fixed for ACPICA version 20170531, closing this report.

**Pull request closed without merging**
