### PR TITLE
Add first batch of RISC-V related definitions

### PR DESCRIPTION
**Pull request by vlsunil**
This is to support the first batch of ECRs for RISC-V support approved by ASWG. 

The changes are primarily, 
1) Update the MADT with a new per-processor interrupt controller for RISC-V.
2) A new static table RHCT is added. So, its definitions, compile/dump functionality and its template need to be defined in acpica.

Below mantis links provide the information about the information about these update. They will be part of next ACPI spec version.
https://mantis.uefi.org/mantis/view.php?id=2348 (MADT)
https://mantis.uefi.org/mantis/view.php?id=2349 (RHCT)

### CODE REVIEW

**Comment by vlsunil** [comment]
MADT updates for iASL is still pending since it needs to be added once https://github.com/acpica/acpica/pull/784 is merged.

**Review by andreiw — APPROVED** [review]
Looks good to me.

**Comment by vlsunil** [comment]
Hi @acpibob 

I have rebased and updated the branch. Andrei Warkentin (Intel) has reviewed and approved the changes. Could you please help review it and merge if no issues? 
Thanks
Sunil

**Comment by sacdintel** [comment]
Hi Sunil,
Thank you very much for the submissions. We will try to get first to #784 and then also this patch and hopefully we will have them merged in our next release which we plan within a month or so from now. Bob or I can let you know if there arise any issues which prevent us from merging either of these pull requests.
- Saket Dumbre

**Comment by vlsunil** [comment]
That's great!, Saket. Thank you very much.

**Comment by vlsunil** [comment]
> Ok, I'll merge this. Probably not for this release of ACPICA (next week), which we are testing now. Thanks, Bob

Hi @acpibob @sacdintel : Is the release done? If this gets merged even if not part of the current release, I think it would help me to update linux patches.
Thanks!

**Comment by sacdintel** [comment]
Hi @vlsunil we are planning on doing the new release next week and if possible we will include your pull request with the new release after we accept and merge it. If not for some logistic reason, we will still merge it soon in the next 2-3 weeks after our ACPICA release and have this PR included as part of the newer release which is targeted for hopefully the end of March 2023! Thanks for your contributions to the RISC-V project, we appreciate it!

**Comment by vlsunil** [comment]
> Hi @vlsunil we are planning on doing the new release next week and if possible we will include your pull request with the new release after we accept and merge it. If not for some logistic reason, we will still merge it soon in the next 2-3 weeks after our ACPICA release and have this PR included as part of the newer release which is targeted for hopefully the end of March 2023! Thanks for your contributions to the RISC-V project, we appreciate it!

Sure, Thanks!

**Comment by vlsunil** [comment]
> Hi @vlsunil we are planning on doing the new release next week and if possible we will include your pull request with the new release after we accept and merge it. If not for some logistic reason, we will still merge it soon in the next 2-3 weeks after our ACPICA release and have this PR included as part of the newer release which is targeted for hopefully the end of March 2023! Thanks for your contributions to the RISC-V project, we appreciate it!

Hi @sacdintel : Gentle ping since the end of march is near.

**Comment by sacdintel** [comment]
Hi Sunil,

I am merging this PR now and it will be part of the new release set for later this week!

**Pull request merged**
