### PR TITLE
NHLT: Drop preliminary support

### PR DESCRIPTION
**Pull request by crojewsk-intel**
Continuation of #881.

Goal of the patchset is to provide clear, readable and actual representation of Non HDAudio Link Table within ACPICA. Specification on which current implementation is based on, does not list all important types and does not inform a reader how things changed throughout the years, unfortunately. Because of numerous conflicts, first patch drops the iASL support entirely for the table ~~and the follow up just re-introduces the types and constants~~. As the work to re-add iASL support is non-trivial and will take more time, decided do this in two-step fashion - add types first, then provide NHLT support in iASL in incremental fashion. This will allow for linux-kernel related changes to be unblocked sooner than later.

Non HDAudio Link Table (NHLT) is designed to separate hardware-related description (registers) from AudioDSP firmware-related one i.e.: pipelines and modules that together make up the audio stream on Intel DSPs. This task is important as same set of hardware registers can be used with different topologies and vice versa, same topology could be utilized with different set of hardware. As the hardware registers description is directly tied to specific platform, intention is to have such description part of low-level firmware e.g.: BIOS.

The initial design has been provided in early Skylake (SKL) days. The audio architecture goes by the name cAVS. SKL is a representative of cAVS 1.5. The table helps describe endpoint capabilities ever since. While Raptorlake (RPL) is the last of cAVS architecture - cAVS 2.5 to be precise - its successor, the ACE architecture which begun with Meteorlake (MTL) inherited the design for all I2S and PDM configurations. These two configurations are the primary targets for NHLT table.

~~As the details changed throughout the years, the re-introduction is stripped off members which are OS-specific or were introduced temporarily.~~

### CODE REVIEW

**Comment by crojewsk-intel** [comment]
@rafaeljw @sacdintel @andy-shev FYI

**Review by andy-shev — COMMENTED** [review]
Sky Lake
Raptor Lake
Meteor Lake

**Comment by crojewsk-intel** [comment]
> Sky Lake
> Raptor Lake
> Meteor Lake

Ack. Fixed in v2.

**Comment by sacdintel** [comment]
Hi @crojewsk-intel like we discussed yesterday, I can close this PR and you can open a new PR later OR I can keep this PR open for now and you can make more edits/amends to this PR by committing more here. Let me know which option works for you, thanks! Regardless, all the NHLT related code first needs to be cleaned up before you add the required structures/code in ACPICA.

**Comment by andy-shev** [comment]
Note, that force push will update the PR automatically.

**Comment by crojewsk-intel** [comment]
Hello, sorry for the delay., overburden a bit. I've removed the commit#2 from the PR.

I believe the table's signature i.e.: ACPI_SIG_NHLT should remain as is. Plus an example in form of TemplateNHLT does not hurt anyone.

**Comment by sacdintel** [comment]
No worries, we can keep this PR open and in progress for you to continue your NHLT work in the near future. You can just add more commits later on to this same PR and keep me updated please. Thanks!

**Review by rafaeljw — COMMENTED** [review]
IMO, the commit title needs to be changed to something like "NHLT: Drop preliminary support" and the paragraph mentioning the follow-up change should be dropped from the changelog.

**Review by rafaeljw — CHANGES_REQUESTED** [review]
Please update the commit as per the previous comment.

**Comment by rafaeljw** [comment]
> Hello, sorry for the delay., overburden a bit. I've removed the commit#2 from the PR.
> 
> I believe the table's signature i.e.: ACPI_SIG_NHLT should remain as is.

I agree.

> Plus an example in form of TemplateNHLT does not hurt anyone.

But does it add any value?

**Comment by rafaeljw** [comment]
> No worries, we can keep this PR open and in progress for you to continue your NHLT
> work in the near future. You can just add more commits later on to this same PR
> and keep me updated please. Thanks!

That's not what was agreed on, however, AFAICS.

The current NHLT-related definitions and code (if any) needs to be removed first, so when the commit is ready (and I'll approve it when that's the case from my perspective), please merge it and close the PR.

There will be another one in the future to add new support, but before it is submitted, the NHLT specification needs to be made publicly available (again), and possibly cleaned up.

If an ACPICA release is made in the meantime, the commit removing the current preliminary NHLT support needs to be included in it.

**Comment by sacdintel** [comment]
OK sure Rafael, sounds good!

**Comment by crojewsk-intel** [comment]
> > Plus an example in form of TemplateNHLT does not hurt anyone.
> 
> But does it add any value?

My thinking was: it brings value _once_ the support is reintroduced and avoids code ping-pong as otherwise the template will part of the future patchset. However, if the decision is have it gone, so be it.

> IMO, the commit title needs to be changed to something like "NHLT: Drop preliminary support" and the paragraph mentioning the follow-up change should be dropped from the changelog.

Ack. Reworded the title as requested. Did some lifting with the commit message too.

**Comment by crojewsk-intel** [comment]
FYI with the change applied, what is left of NHLT is:
```
~/reef/acpica/source$ ag nhlt
common/ahtable.c
241:    {ACPI_SIG_NHLT, "Non HD Audio Link Table"},

common/dmtable.c
676:    {ACPI_SIG_NHLT, NULL,                   NULL,           NULL,           NULL},

include/actbl2.h
186:#define ACPI_SIG_NHLT           "NHLT"      /* Non HD Audio Link Table */
```

**Comment by rafaeljw** [comment]
> FYI with the change applied, what is left of NHLT is:
> 
> ```
> ~/reef/acpica/source$ ag nhlt
> common/ahtable.c
> 241:    {ACPI_SIG_NHLT, "Non HD Audio Link Table"},
> 
> common/dmtable.c
> 676:    {ACPI_SIG_NHLT, NULL,                   NULL,           NULL,           NULL},
> 
> include/actbl2.h
> 186:#define ACPI_SIG_NHLT           "NHLT"      /* Non HD Audio Link Table */
> ```

This is fine, but please update the commit changelog as requested.

**Comment by crojewsk-intel** [comment]
> This is fine, but please update the commit changelog as requested.

I did update it though. Is its current state still lackluster?

**Comment by rafaeljw** [comment]
> > This is fine, but please update the commit changelog as requested.
> 
> I did update it though. Is its current state still lackluster?

It is OK, already approved.

**Pull request merged**
