### PR TITLE
Acpica Endtag

### PR DESCRIPTION
**Pull request by zetalog**
Cleanup to split the code that requires to validate resource checksum from the code that mustn't validate resource checksum.

### CODE REVIEW

**Comment by zetalog** [comment]
Update to talk about the real issues related to EndTag rather than talking about resource checksum validation which might have been proven to be unsupported by industry. Dropped resource checksum validation related enhancements.

**Comment by timofonic** [comment]
@acpibob @zetalog Any hopes for this code improvement and fixes to get merged upstream? Any news?

**Comment by acpibob** [comment]
Closing for now. This functionality/code is very sensitive to changes, and we don't want to make changes just for the sake of small improvement. At this time, there are not reported problems with the existing code.

**Comment by mirh** [comment]
Guess like it makes sense, though I'd hope you have at least a note/issue somewhere tracking this.

**Comment by acpibob** [comment]
We know where it is.

**Pull request closed without merging**
