### PR TITLE
Acpica trivial

### PR DESCRIPTION
**Pull request by zetalog**
Before releasing 201612xx, maybe we can have something in this pull request merged.
Let me send it here to have it reviewed.
I'm enhancing these patches these days.

Thanks
Lv

### CODE REVIEW

**Comment by acpibob** [comment]
You had better do this quickly, release will be this Thursday, Friday at the very latest

  *
  *
  *
  *   acpiexec: Move an acpiexec specific purposed new line to acpiexec specific file
What is this?


  *   Utilities: Add ACPI_DO_ONCE macros
What is this?


  *   Dispatcher: Introduce timeout mechanism for infinite loop detection

Not an emergency since we have already introduced a workaround for now.

**Comment by zetalog** [comment]
Hi, Bob

**Comment by zetalog** [comment]
Hi, Bob

Pull request refreshed.
I also tested them with MSVC 2008, no porting issues can be seen for Kees/Emese's commit.

Thanks
Lv

**Comment by zetalog** [comment]
This pull request only contains community materials.
Patch descriptions are updated so that the original discussions can be reached.

**Pull request merged**
