### PR TITLE
Acpica endian

### PR DESCRIPTION
**Pull request by zetalog**
This patchset is a demonstration to add combined unalignement/endianness support for ACPICA.

The new feature can be an opt-in feature.
After we cleaned up all of the existing code, the old features could then opt-out.

### CODE REVIEW

**Comment by timofonic** [comment]
@zetalog @acpibob @kkamagui @SchmErik Any news about this? I'm amazed this is open since 2014 :O

**Comment by kkamagui** [comment]
I am afraid that there is nothing new.

I  have been solving a critical security issue in BIOS/UEFI firmware since last December.

It seems that it is worth to be merged and after solving BIOS/UEFI issue, I will keep monitoring it.

**Comment by acpibob** [comment]
Closing for now, until it is actually needed. We don't know of any outstanding requests for this support.

**Comment by hanetzer** [comment]
> Closing for now, until it is actually needed. We don't know of any outstanding requests for this support.

Have an outstanding request. Coreboot uses it, and I can't build coreboot roms with a big endian linux system
on a talos ii power9 system without this.

**Comment by acpibob** [comment]
What exactly needs to be done?

**Comment by hanetzer** [comment]
> What exactly needs to be done?

Not sure, not familiar with the code, but it needs to be able to 1. run on big endian
hosts and 2. produce proper code when run on big endian hosts.

**Comment by acpibob** [comment]
I assume (1) means "be able to build on big endian hosts. (2): as far as actual AML code, the code (and ACPI tables) will be the same regardless of the endianness. So, what is failing?

**Comment by hanetzer** [comment]
> I assume (1) means "be able to build on big endian hosts. (2): as far as actual AML code, the code (and ACPI tables) will be the same regardless of the endianness. So, what is failing?

It will build on big endian hosts, but attempting to execute iasl will just return a message that
it is not supported on big endian.

**Comment by acpibob** [comment]
could you please try this:

open compiler/aslmain.c, goto function "main"
comment out call to "UtIsBigEndianMachine", and the block underneath the call.
rebuild the compiler and test.

thanks, bob

**Comment by rafaeljw** [comment]
This PR is outdated and so it can be closed.

**Comment by acpibob** [comment]
Closing, see Rafael's comment above.

**Pull request closed without merging**
