### PR TITLE
* use ACPI_ERROR() instead of fprintf() as the OS might not use or pr…

### PR DESCRIPTION
**Pull request by miray-sb**
…ovide fprintf() and/or stderr

### CODE REVIEW

**Comment by acpibob** [comment]
Got it, thanks.

**Comment by miray-sb** [comment]
Thank you for merging :)

**Comment by acpibob** [comment]
Is this change in addition to the first pull request you made?
Thanks,
Bob


From: miray-sb ***@***.***>
Sent: Tuesday, April 05, 2022 1:05 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] * use ACPI_ERROR() instead of fprintf() as the OS might not use or pr… (PR #768)


…ovide fprintf() and/or stderr

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/acpica/acpica/pull/768

Commit Summary

  *   c3e6f02<https://github.com/acpica/acpica/pull/768/commits/c3e6f020575b991ff3243c2355d8550686a2de93> * use ACPI_ERROR() instead of fprintf() as the OS might not use or provide fprintf() and/or stderr

File Changes

(1 file<https://github.com/acpica/acpica/pull/768/files>)

  *   M source/components/executer/exconfig.c<https://github.com/acpica/acpica/pull/768/files#diff-727a7aadaadfff85d053c58f6a099f93172f4c6679ea652f8ee524383f95cd92> (2)

Patch Links:

  *   https://github.com/acpica/acpica/pull/768.patch
  *   https://github.com/acpica/acpica/pull/768.diff

**Comment by miray-sb** [comment]
How do you mean that?

We updated our own copy of ACPICA to the current release and noticed this problem which had been introduced since our last update (were we had encountered the other issues the previous merge request addressed).

**Pull request merged**
