### PR TITLE
RISC-V: Code First ECR for RINTC Affinity Structure Support 

### PR DESCRIPTION
**Pull request by xiaobo55x**
This PR adds the SRAT RINTC affinity structure  which was approved recently by a CodeFirst ECR(Mantis ID: [2433](https://mantis.uefi.org/mantis/view.php?id=2433)).
https://drive.google.com/file/d/1YTdDx2IPm5IeZjAW932EYU-tUtgS08tX/view?usp=sharing

### CODE REVIEW

**Comment by xiaobo55x** [comment]
Hi @sacdintel,

Could you help review this patch?

Thanks,
Haibo

**Comment by sacdintel** [comment]
Sure, as soon as I'm back to work from my leave in about 9-10 days more,I'll review and then merge this and some other PRs which I believe are ready. Thanks for your patience!

**Comment by xiaobo55x** [comment]
> Sure, as soon as I'm back to work from my leave in about 9-10 days more,I'll review and then merge this and some other PRs which I believe are ready. Thanks for your patience!

Ok, thanks!

**Comment by sacdintel** [comment]
I requested access to the Google drive link, but it is using my personal Google account as an Intel employee, I have only Microsoft suite of productivity and email environment! Thanks!

**Comment by xiaobo55x** [comment]
> I requested access to the Google drive link, but it is using my personal Google account as an Intel employee, I have only Microsoft suite of productivity and email environment! Thanks!

I have added you(saketdumbre@gmail.com) to the viewers list. Please let me know if you still can't access it.

**Comment by sacdintel** [comment]
LGTM! Thanks!

**Comment by xiaobo55x** [comment]
> LGTM! Thanks!

Thanks for the review!

**Pull request merged**
