### PR TITLE
iASL: Add support for the SDEI table (v2)

### PR DESCRIPTION
**Pull request by james-morse-arm**
ACPI 6.2 adds support for the Software Delegated Exception Interface,
which is described by "Software Delegated Exception Interface (SDEI)"
ARM DEN0054A.

Add the necessary types in the ACPICA header files and support for
compiling/decompiling the table.

To avoid a dummy Compile method, that just returns OK, allow 
DTCompileDataTable() to compile simple-tables that only have a header.

### CODE REVIEW

**Comment by acpibob** [comment]
Couple more things.
Add new table to ahtable.c

Status = DtCompileTable (FieldList, TableData->TableInfo,  
                                        &Subtable, TRUE);  

Indentation on this one, should be:

Status = DtCompileTable (FieldList, TableData->TableInfo,  
    &Subtable, TRUE);

**Comment by acpibob** [comment]
needs 4-space indent on second line (gets stripped in the github software)
Status = DtCompileTable (FieldList, TableData->TableInfo,
 &Subtable, TRUE);

**Comment by acpibob** [comment]
When the commits are updated, we can merge them.

**Comment by james-morse-arm** [comment]
Hi Robert,

acpibob wrote:
> When the commits are updated, we can merge them.

I don't understand, I've probably done something wrong with the github interface!
Yesterday I did a force-push (partly to see what happened) to rebase and fix the ahtable.c and indentation problems you pointed to. I see these changes in e3c74a3d6 and 5ad4f0b7, which are the only two commits listed under:
https://github.com/acpica/acpica/pull/279/commits

Where have I gone wrong!?

Thanks,

James

**Comment by acpibob** [comment]
I was just asking if it is ready for merging. If you've made the changes, I can take it today.

**Pull request merged**
