### PR TITLE
ACPI 6.4 changes

### PR DESCRIPTION
**Pull request by SchmErik**
This pull request contains several changes that add iASL support for the ACPI 6.4 specification. This pull request includes new hardware ID's, UUID's, name object reservations, and sub-tables for existing data tables.

### CODE REVIEW

**Comment by SchmErik** [comment]
@acpibob I forgot to add new structs for acpisrc. I'll update and send another message once I do so....

**Comment by SchmErik** [comment]
OK, added acpisrc changes. This is good to go now

**Comment by SchmErik** [comment]
@acpibob this has everything except phat and pmtt

**Comment by acpibob** [comment]
Will you get to those?

**Pull request merged**
