### PR TITLE
Fix build on a platform where char is unsigned.

### PR DESCRIPTION
**Pull request by juikim**

### CODE REVIEW

**Comment by juikim** [comment]
Without this fix, it fails to build like this:
```
In file included from ../../../source/compiler/aslcompiler.l:864:
../../../source/compiler/aslsupport.l:550:48: error: comparison of constant -1 with expression of type 'char' is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    for (i = 0; (yytext[i] != 0) && (yytext[i] != EOF); i++)
                                     ~~~~~~~~~ ^  ~~~
1 error generated.
```

**Comment by SchmErik** [comment]
Thank you for your pull request. Could you change your while loop to a for loop?

**Comment by juikim** [comment]
I realized that the fix is not entirely correct.  I'll open a new issue soon.

**Comment by juikim** [comment]
Please see #341.

**Pull request closed without merging**
