### PR TITLE
Remove leftover dead code

### PR DESCRIPTION
**Pull request by ElyesH**
Signed-off-by: Elyes Haouas <ehaouas@noos.fr>

### CODE REVIEW

**Comment by acpibob** [comment]
Please test this.
bob

**Comment by ElyesH** [comment]
Using `Wno-dangling-pointer', the build test is ok with gcc-12.

However, I'm getting an error . This error is not related to current patch but to gcc-12 
`obj/acpiexec ../../../source/components/utilities/utdebug.c
../../../source/components/utilities/utdebug.c: In function ‘AcpiUtInitStackPtrTrace’:
../../../source/components/utilities/utdebug.c:188:31: error: storing the address of local variable ‘CurrentSp’ in ‘AcpiGbl_EntryStackPointer’ [-Werror=dangling-pointer=]
  188 |     AcpiGbl_EntryStackPointer = &CurrentSp;
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../../../source/components/utilities/utdebug.c:185:29: note: ‘CurrentSp’ declared here
  185 |     ACPI_SIZE               CurrentSp;
      |                             ^~~~~~~~~
In file included from ../../../source/include/acpi.h:173,
                 from ../../../source/components/utilities/utdebug.c:154:
../../../source/include/acglobal.h:335:41: note: ‘AcpiGbl_EntryStackPointer’ declared here
  335 | ACPI_GLOBAL (ACPI_SIZE *,               AcpiGbl_EntryStackPointer);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
../../../source/include/acpixf.h:188:17: note: in definition of macro ‘ACPI_GLOBAL’
  188 |     extern type name
      |                 ^~~~
cc1: all warnings being treated as errors
make[1]: *** [../Makefile.rules:20 : obj/utdebug.o] Erreur 1`

**Comment by acpibob** [comment]
I think this is supposedly fixe in pull request 835.

We will do another release of ACPICA sometime next week.

Bobb

**Comment by ElyesH** [comment]
I've used commit 1aaa3da8c7dd710eeb68fbeeda0b25f10009628f and the error related to `dangling-pointer` isn't fixed.
Here is more information about gcc used version:
`$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-12-bTRWOB/gcc-12-12.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-12-bTRWOB/gcc-12-12.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14) `

**Comment by acpibob** [comment]
We will have to track down the original poster for the patch.
Thanks,
Bob

**Comment by acpibob** [comment]
I'd like to leave the code under the #ifdef ACPI_OBSOLETE_FUNCTIONS statements for now, in case they are needed again, or as example code for how to implement the functionality.

**Comment by ElyesH** [comment]
Sure.
We can close current "pull".
Thank you.

**Pull request closed without merging**
