### PR TITLE
disable rt on Haiku

### PR DESCRIPTION
**Pull request by korli**

### CODE REVIEW

**Comment by sacdintel** [comment]
Could you please provide a brief description of this PR? What is it that it intends to achieve? What was the motivation behind that change? Some other points I need to know to review and merge it? Thanks!

**Comment by korli** [comment]
> Could you please provide a brief description of this PR? What is it that it intends to achieve? What was the motivation behind that change? Some other points I need to know to review and merge it? Thanks!

Like for APPLE and QNX, librt doesn't exist on Haiku.

**Comment by sacdintel** [comment]
Thanks for the clarification!

**Comment by sacdintel** [comment]
Merging it now, LGTM!

**Pull request merged**
