### PR TITLE
Acpica Gpe

### PR DESCRIPTION
**Pull request by zetalog**
This patchset can help to avoid all kinds of GPE losses:
1. Gpe shouldn't be cleared which may cause GPE loss, but should be handled.
2. Edge-triggered GPE should be polled once right after being enabled.

However in order for GPE handler to be safe for both IRQ context and task context, GPE handling should be parallelized - achieved via per-GPE bit handling.

### CODE REVIEW

**Comment by zetalog** [comment]
Hi, Bob

I need to do the followings:

1. As Linux contains the following fix, I need to confirm if releasing these patches won't cause issues. Especially, I need to check if a handler will be invoked twice for an edge-triggered GPE when both fixes are there.
2. I'll check if I can make GPE handling more parallel (probably, lock only one GPE handling process from checking STS, clearing STS, invoking the handler). It seems possible as GPE is W1C, we should be able to handle one single GPE with a GpeLock locked period and handle the other GPE using another locked period. This could help us to simplify GPE handling code a lot and eliminates some duplicates.

So though the bug fixes are confirmed to be working. Let me confirm again and improve them before they are upstreamed.
If 1 is confirmed to be OK, I'll prepend Rafael's change before these fixes and without proceeding to 2 (2 can be done in the future).
If 1 is not OK, I'll continue to do 2 and simplify the code to have both logics handled in a single way.

**Comment by zetalog** [comment]
OK, the potential issue is fixed.
However I need to run it with Linux.
Will report back if it's working.

Thanks
Lv

**Comment by zetalog** [comment]
Hi, Bob

This PR is ready from my side.
I've tested it with Linux and no issue can be seen so far.

Thanks
Lv

**Comment by acpibob** [comment]
This change causes a bunch of GPEs and messages from AcpiExec, see below. I may have to revert this.

Input file dsdt.aml, Length 0x3D (61) bytes

ACPI: RSDP 0x00000000004949B4 000024 (v02 Intel )
ACPI: XSDT 0x0000000000611860 000034 (v00 Intel  AcpiExec 00001001 INTL 20170831)
ACPI: FACP 0x00000000004949D8 000114 (v05 Intel  AcpiExec 00001001 INTL 20170831)
ACPI: DSDT 0x0000000000611808 00003D (v02 Intel  _DSDT_01 00000001 INTL 20170831)
ACPI: FACS 0x0000000000494B10 000040
Initializing General Purpose Events (GPEs):
    Initialized GPE 00 to 1F [_GPE] 4 regs on interrupt 0x0 (SCI)
    Initialized GPE 64 to 263 [_GPE] 64 regs on interrupt 0x0 (SCI)

Initializing Namespace objects:
Table [DSDT: _DSDT_01] (id 01) -    1 Objects with   0 Devices,   0 Regions,    1 Methods (0/1/0 Serial/Non/Cvt)
ACPI: Executed 1 blocks of module-level executable AML code
ACPI: 1 ACPI AML tables successfully acquired and loaded

Completing Region/Field/Buffer/Package initialization:
    Initialized 0/0 Regions 0/0 Fields 0/0 Buffers 0/0 Packages (10 nodes)
Initializing Device/Processor/Thermal objects and executing _INI/_STA methods:
    Executed 0 _INI methods requiring 0 _STA executions (examined 2 objects)
ACPI Exec: Global Event Handler received: Type GPE Number 00 Dev 006111C8
ACPI Exec: GPE Handler received GPE 00 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 01 Dev 006111C8
ACPI Exec: GPE Handler received GPE 01 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 02 Dev 006111C8
ACPI Exec: GPE Handler received GPE 02 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 03 Dev 006111C8
ACPI Exec: GPE Handler received GPE 03 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 04 Dev 006111C8
ACPI Exec: GPE Handler received GPE 04 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 05 Dev 006111C8
ACPI Exec: GPE Handler received GPE 05 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 06 Dev 006111C8
ACPI Exec: Global Event Handler received: Type GPE Number 07 Dev 006111C8
ACPI Error: No handler or method for GPE 07, disabling event (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 18 Dev 006111C8
ACPI Exec: Global:    Received a System Notify on [_SB_] 00611258 Value 0x02 (Device Wake)
ACPI Error: ACPI Exec: Handler 2: Received a System Notify on [_SB_] 00611258 Value 0x02 (Device Wake)
No handler or method for GPE 18, disabling eventACPI Exec: Handler 1: Received a System Notify on [_SB_] 00611258 Value
0x02 (Device Wake)
ACPI Exec: Global:    Received a System Notify on ["\" ] 00496580 Value 0x02 (Device Wake)
 (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 19 Dev 006111C8
ACPI Exec: GPE Handler received GPE 19 (GPE block _GPE)
ACPI Exec: Global Event Handler received: Type GPE Number 1A Dev 006111C8
ACPI Error: No handler or method for GPE 1A, disabling event (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 1B Dev 006111C8
ACPI Error: No handler or method for GPE 1B, disabling event (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 1C Dev 006111C8
ACPI Error: No handler or method for GPE 1C, disabling event (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 1D Dev 006111C8
ACPI Error: No handler or method for GPE 1D, disabling event (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 1E Dev 006111C8
ACPI Error: No handler or method for GPE 1E, disabling event (20170831/evgpe-1047)
ACPI Exec: Global Event Handler received: Type GPE Number 1F Dev 006111C8
ACPI Error: No handler or method for GPE 1F, disabling event (20170831/evgpe-1047)

**Comment by zetalog** [comment]
They are expected.
We'll poll event once it is enabled, so if GPE registers return enabled and flagged, we'll handle it.

While in AcpiOsReadPort implemented by acpiexec, we returned 1 for all registers, causing it's detected as enabled and flagged.
If you don't like the increased messages, we can just return 0 from AcpiOsReadPort.

**Pull request merged**
