### PR TITLE
Fix multiple issues with printing decoded MPAM tables

### PR DESCRIPTION
**Pull request by punitagrawal**
The ACPI table decoding functionality is key to debugging firmware advertised functionality and OS enablement. I noticed a few issues with ACPI MPAM decoding when investigating a particular Arm platform where the firmware provides this description.

The patches in this merge request fix the issues and have been tested with MPAM tables on two systems I have access to. Please consider merging if there are no issues.

### CODE REVIEW

**Comment by cworth-gh** [comment]
Thanks. This branch fixes the parsing of the MPAM table for me.

Without this branch, using iasl built from the main branch to parse the MPAM table results in an error of:

`/**** ACPI table terminates in the middle of a data structure! */`

But with this branch, the table is parsed correctly.

Tested-by: Carl Worth <cworth@amperecomputing.com>

-Carl

**Comment by sacdintel** [comment]
Hi Punit,

It looks good to me, but can you also please update the MPAM table template in dttemplate.h and I will merge it asap! Thanks a lot!

**Comment by punitagrawal** [comment]
Hi Saket,

> It looks good to me, but can you also please update the MPAM table template in dttemplate.h and I will merge it asap! Thanks a lot!

There doesn't seem to be any issue with the template generated by `iasl -T MPAM`.  What kind of update is needed?

_I am not familiar with the templating functionality as I've mostly used acpica for debugging_

**Comment by punitagrawal** [comment]
Hi Saket,

Thanks for the context. AFAICT the patches should not change the MPAM tables. Perhaps you are thinking of the commit fixing the typo in the variable name of acpica code - but that shouldn't leak into to the table itself.

In any case, I've now added a commit to update the MPAM template as requested. Hope that helps to verify that there are no breaking changes to the table disassembly / compilation. Based on the diff, the only changes are to the checksum and version of the `iasl` used; the rest of the template stays unmodified.

**Comment by sacdintel** [comment]
Thanks a lot @punitagrawal for the contribution and I really appreciate the template change and your understanding of the reason behind my request. Thanks to also @cworth-gh for testing this PR out! LGTM, so I am merging it now!

**Pull request merged**
