### PR TITLE
Acpica package

### PR DESCRIPTION
**Pull request by zetalog**
BZ 1333.

This patch changes PackageElement parsing according to the validated Windows behavior. It seems Windows always converts NameString in Package into String, so that when an OSPM driver invokes a package returning control method later, forward references can be allowed.

However, in the evaluation result, we still convert String into ObjectReference to be old ACPICA compliant (not to break Linux).

Reported by Peter Wu
Fixed by Lv Zheng
Link: https://bugs.acpica.org/show_bug.cgi?id=1333
Link: https://github.com/Bumblebee-Project/bbswitch/issues/142

### CODE REVIEW

**Comment by zetalog** [comment]
Namespace: Add an API to be used by external users to resolve in-pack…  …	

This patch is requested by Linux guys, they failed to solve NameStrings contained in the serial bus and the gpio resources using existing APIs.
OTOH, this API may be used by OSPMs to solve in package NameString when we disable the "AcpiGbl_EnablePredefinedReferences" quirk, thus facilitates new driver development.

Thanks

**Comment by zetalog** [comment]
Namespace: Add wrapper to resolve NameString to ObjectReference for p…  …	

In this commit, all package returning predefined objects are worked around using "AcpiGbl_EnablePredefinedReferences".
For non-predefined objects, we needn't do that because:
1. package returning non-predefined evaluation is very rare (possibly only in WMI drivers).
2. AML developer may have implemented such objects with String instead of NameString, so the OSPM driver may have already been ready.
3. If we saw such problems, we can fix them, I'm checking this in the Linux code base.

**Comment by zetalog** [comment]
Refreshed to make this fix no longer dependent on the operand object reference counting issue.

**Comment by zetalog** [comment]
Can see aslts increased after merging this.
				old		new
name			0		1
referernce		5		26
region			3		4
misc			1		5
rstore			6		5
roptional		2		4
rexplicitconv	2		6
extra_aslts		15		17
bdemo			43		52

Probably because ObjectType(Package[0]) == String/Reference difference.
I'll append ASLTS cleanups with this commit.

**Comment by zetalog** [comment]
It looks it is not that simple.
We still need to validate Windows behavior for this case.
Especially,
1. before/after the package element (let me call it old) is referenced, what the ObjectType(old) will be?
2. after Copy/Store the package element (old) to a new object (let me call it new), before/after the new object is referenced, what the ObjectType(new) will be? And result of some other opcodes that are invoked with "new" should also be validated.

**Comment by zetalog** [comment]
I validated using qemu.

The following ASL case:
Name (FRPG, Package (1) {
	OBRF,
})
Name (OBRF)
Name (OBCP)
Store (Index (FRPG, 0), OBCP)
Just returns exception, whatever I put it into MLC or a method.

And moving Name (OBRF) prior to FRPG, for example:
Name (OBRF)
Name (BRPG, Package (1) {
	OBRF,
})
Name (OBCP)
Store (Index (BRPG, 0), OBCP)
Also returns exception, whatever I put it into MLC or a method.

Windows simply doesn't allow storing an in-package reference to another object...

So the increased ASLTS failures are actually wrong, and we can ignore it.

**Comment by zetalog** [comment]
It seems the pull request is safe, while ASLTS need to be updated.
However let me confirm 1 failure by 1 failure before merging.

**Comment by zetalog** [comment]
Fixes for old issues can be found in #252 .

**Comment by zetalog** [comment]
Current failure case comparison (s32 as an example):
```
*** fixed/opt/32/__STATUS_OF_TESTS	2017-04-18 17:06:41.797401250 +0800
--- unfixed/opt/32/__STATUS_OF_TESTS	2017-04-19 09:46:32.115176449 +0800
***************
*** 210 ****
! [ACPI Debug]  ":STST:functional:reference:m253:PASS:"
--- 210 ----
! [ACPI Debug]  ":STST:functional:reference:m253:FAIL:Errors # 1E 00 00 00:"
=> Lv: Fixed by #252
***************
*** 247 ****
! [ACPI Debug]  ":STST:functional:region:m702:PASS:"
--- 247 ----
! [ACPI Debug]  ":STST:functional:region:m702:FAIL:Errors # 02 00 00 00:"
=> Lv: Fixed by #252
***************
*** 1478 ****
! [ACPI Debug]  ":STST:complex:rstore:RES0-m689-m020-NN:PASS:"
--- 1478 ----
! [ACPI Debug]  ":STST:complex:rstore:RES0-m689-m020-NN:FAIL:Errors # 51 00 00 00:"
=> Lv: Fixed by #252
***************
*** 1480 ****
! [ACPI Debug]  ":STST:complex:rstore:RES0-m689-m020-LN:PASS:"
--- 1480 ----
! [ACPI Debug]  ":STST:complex:rstore:RES0-m689-m020-LN:FAIL:Errors # 33 00 00 00:"
=> Lv: Fixed by #252
***************
*** 1506 ****
! [ACPI Debug]  ":STST:complex:rexplicitconv:m693-S-N:PASS:"
--- 1506 ----
! [ACPI Debug]  ":STST:complex:rexplicitconv:m693-S-N:FAIL:Errors # 31 00 00 00:"
=> Lv: Fixed by #252
***************
*** 1632,1634 ****
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4b7:FAIL:Errors # 16 00 00 00:"
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4b8:FAIL:Errors # 13 00 00 00:"
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4b9:FAIL:Errors # 14 00 00 00:"
--- 1632,1634 ----
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4b7:FAIL:Errors # 19 00 00 00:"
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4b8:FAIL:Errors # 16 00 00 00:"
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4b9:FAIL:Errors # 17 00 00 00:"
=> Lv: Error decreased, should due to #252.
***************
*** 1636,1637 ****
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4bb:FAIL:Errors # 13 00 00 00:"
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4bc:FAIL:Errors # 13 00 00 00:"
--- 1636,1637 ----
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4bb:FAIL:Errors # 16 00 00 00:"
! [ACPI Debug]  ":STST:exceptions:exc_operand2:m4bc:FAIL:Errors # 16 00 00 00:"
=> Lv: Error decreased, should due to #252.
***************
*** 1640 ****
! [ACPI Debug]  ":STST:exceptions:exc_result2:RES5-m689-m020-NN:FAIL:Errors # 1C 00 00 00:"
--- 1640 ----
! [ACPI Debug]  ":STST:exceptions:exc_result2:RES5-m689-m020-NN:FAIL:Errors # 0F 00 00 00:"
=> Lv: Error increased, should keep on auditting.
***************
*** 1642 ****
! [ACPI Debug]  ":STST:exceptions:exc_result2:RES5-m689-m020-LN:FAIL:Errors # 1A 00 00 00:"
--- 1642 ----
! [ACPI Debug]  ":STST:exceptions:exc_result2:RES5-m689-m020-LN:FAIL:Errors # 12 00 00 00:"
=> Lv: Error increased, should keep on auditting.
***************
*** 2125 ****
! [ACPI Debug]  ":STST:bdemo:Demo of bug 274:mc74:FAIL:Errors # 01 00 00 00:"
--- 2125 ----
! [ACPI Debug]  ":STST:bdemo:Demo of bug 274:mc74:PASS:"
=> Lv: Error due to slack mode bug, cannot be fixed. The difference cannot be seen for n32/n64 tests.
```

**Comment by zetalog** [comment]
To Bob:

The easier way to confirm the aslts change in this pull request is:
1. run aslts.sh before applying the commits, save the tmp/RESULTS/2xxxxx folder into old
2. run aslts.sh after applying the commits, save the tmp/RESULTS/2xxxxx folder into new
3. diff new/[nopt|opt]/[32|64]/__STATUS_OF_TESTS old/[nopt|opt]/[32|64]/__STATUS_OF_TESTS diff_file

Then the improved aslts result can be confirmed via diff_file.

**Comment by zetalog** [comment]
By stop using "-ep" for ASLTS, only fixed by module level support cases broken again.
Include several table/exc_table/bdemo cases, and entiire "module" suite.

And previously we've proven that the new approach doesn't actually break aslts, all breakages are because of ASLTS cases themselves are written in a non-Windows compliant way.

So it should be safe to merge this pull request.
I collect those ASLTS fixes that are proven to be good.
But for those we still need to validate, I'll prepare a separate pull reqeust.

**Comment by XVilka** [comment]
Is there any hope for those patches to get merged?

**Comment by acpibob** [comment]
support for forward references from package elements was released in version 20170728. The support is transparent and no changes to ASLTS are required.

**Comment by timofonic** [comment]
@zetalog @acpibob So what's missing? Why is this PR open?

**Comment by timofonic** [comment]
I see there are conflicting files too...

**Comment by SchmErik** [comment]
I believe we just forgot to close it... We took @acpibob's solution to solve this issue

**Comment by zetalog** [comment]
What have been done in the PR is determined not to go upstream for now.
Let me close the PR.

**Pull request closed without merging**
