### PR TITLE
Remove an old ASL compiler manual

### PR DESCRIPTION
**Pull request by ahs3**
While the manual may still be useful, the licensing on it is completely
unclear.  Until such time as distribution rights are properly clarified,
remove this file from the git repository so that open source projects
can freely use the remainder of the project code.

NB: this file only showed up in the acpitests-*.tar.gz tarball, and
not the acpica-unix2*.tar.gz tarball.

Signed-off-by: Al Stone <ahs3@redhat.com>

### CODE REVIEW

**Comment by acpibob** [comment]
Is this what you are talking about (This is the only legal info I can find in the doc)?

Information in this document is provided in connection with Intel® products. No license, express or implied, by estoppel or otherwise, to any intellectual
property rights is granted by this document. Except as provided in Intel’s Terms and Conditions of Sale for such products, Intel assumes no liability
whatsoever, and Intel disclaims any express or implied warranty, relating to sale and/or use of Intel products including liability or warranties relating to
fitness for a particular purpose, merchantability, or infringement of any patent, copyright or other intellectual property right. Intel products are not
intended for use in medical, life saving, or life sustaining applications.
Intel may make changes to specifications and product descriptions at any time, without notice.
Designers must not rely on the absence or characteristics of any features or instructions marked "reserved" or "undefined." Intel reserves these for
future definition and shall have no responsibility whatsoever for conflicts or incompatibilities arising from future changes to them.
The iASL compiler may contain design defects or errors known as errata which may cause the product to deviate from published specifications.
Current characterized errata are available on request.


From: Al Stone ***@***.***>
Sent: Tuesday, July 13, 2021 2:18 PM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] Remove an old ASL compiler manual (#704)


While the manual may still be useful, the licensing on it is completely
unclear. Until such time as distribution rights are properly clarified,
remove this file from the git repository so that open source projects
can freely use the remainder of the project code.

NB: this file only showed up in the acpitests-.tar.gz tarball, and
not the acpica-unix2.tar.gz tarball.

Signed-off-by: Al Stone ***@***.******@***.***>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/acpica/acpica/pull/704

Commit Summary

  *   Remove an old ASL compiler manual

File Changes

  *   D tests/aslts/src/runtime/collections/Identity2MS/abbu/UTILITY/AslCompiler.pdf<https://github.com/acpica/acpica/pull/704/files#diff-16ca69a0355df12fe8788953a98abb7a801fbd260e4cdbe407c9dc58a454729e> (0)

Patch Links:

  *   https://github.com/acpica/acpica/pull/704.patch
  *   https://github.com/acpica/acpica/pull/704.diff

**Comment by ahs3** [comment]
That's it exactly.  This is the key sentence: "No license, express or implied, by estoppel or otherwise, to any intellectual property rights is granted by this document."  It could be taken as pretty restrictive.  It's also a mystery why it ended up in such an odd location in the git tree :-).

**Comment by acpibob** [comment]
We've decided that we aren't going to do anything about this until we get an opinion from our legal department.

>odd location in the git tree
what do you mean by this? The documentation all appear under acpica/documents.

**Comment by acpibob** [comment]
>so that open source projects
can freely use the remainder of the project code

I don't see how the license on this one document affects the use of the remainder of the project code. BTW, we've never had a comment/issue on this in over 20 years.

**Comment by ahs3** [comment]
> We've decided that we aren't going to do anything about this until we get an opinion from our legal department.
> 
> > odd location in the git tree
> > what do you mean by this? The documentation all appear under acpica/documents.

This PDF file was in the acpitests tarball, not acpica-unix2.   The file was in tests/aslts/src/runtime/collections/Identity2MS/abbu/UTILITY/, not acpica/documents.

**Comment by ahs3** [comment]
> > so that open source projects
> > can freely use the remainder of the project code
> 
> I don't see how the license on this one document affects the use of the remainder of the project code. BTW, we've never had a comment/issue on this in over 20 years.

This does not affect the use of the remainder of the project code.  Our license reviewers are recommending we do not redistribute this one file only.

**Comment by acpibob** [comment]
Here’s an update from our legal department (new text is prefixed with “>”)

Information in this document is provided in connection with Intel® products. No license, express or implied, by estoppel or otherwise, to any intellectual property rights is granted by this document

  *   with the sole exceptions that a) you may republish an unmodified copy and b) code included in this document is licensed subject to Zero-Clause BSD open source >license (OBSD).
>You may create software implementations based on this document and in compliance with the foregoing.
  *   No rights are granted to create modifications or derivatives of this document.

Except as provided in Intel’s Terms and Conditions of Sale for such products, Intel assumes no liability whatsoever, and Intel disclaims any express or implied warranty, relating to sale and/or use of Intel products including liability or warranties relating to fitness for a particular purpose, merchantability, or infringement of any patent, copyright or other intellectual property right. Intel products are not intended for use in medical, life saving, or life sustaining applications.

Intel may make changes to specifications and product descriptions at any time, without notice.

Designers must not rely on the absence or characteristics of any features or instructions marked "reserved" or "undefined." Intel reserves these for future definition and shall have no responsibility whatsoever for conflicts or incompatibilities arising from future changes to them.

The iASL compiler may contain design defects or errors known as errata which may cause the product to deviate from published specifications. Current characterized errata are available on request.

Copyright © 2000 - 2017 Intel Corporation

*Other brands and names are the property of their respective owners.

**Comment by acpibob** [comment]
Does this work for you?
bob

**Comment by ahs3** [comment]
> Does this work for you?
> bob

That looks better. I'll double check with the folks that complained. Why is it in the acpitests tarball, though?

**Comment by acpibob** [comment]
I'm not really sure why we put that .pdf file under acpitests. Note, it looks like the other documents (acpica-reference), etc. don't get copied into any of the tarballs -- probably because they are large files, and can be grabbed individually from the acpica website (acpica.org/documentation).

**Comment by ahs3** [comment]
For simplicity's sake (and tarball size), just removing this PDF works for me.  I'd rather it was on the web site anyway.

**Comment by acpibob** [comment]
Ok, you got it.
Thx,
Bob

**Comment by ahs3** [comment]
You rock, dude.

Many thanks.

**Comment by acpibob** [comment]
Fixed for next release of ACPICA.

**Pull request closed without merging**
